# Generated by Django 3.2.8 on 2021-10-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211025_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='message',
        ),
        migrations.AddField(
            model_name='channel',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.channel'),
            preserve_default=False,
        ),
    ]
