# Generated by Django 3.2.8 on 2021-10-25 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211025_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main_app.message'),
        ),
    ]
